### PR TITLE
make Pinner an abstract class than we can extend with any HTTP client.

### PR DESCRIPTION
**Pull request by gordielachance**
Hi dzafel !
I would like to use another HTTP client than Guzzle.
So I abstracted your class Pinner and created a new child class Pinner_Guzzle in another file.
I really think this is a good idea to keep the code clean and allow users to extend it.

I would be glad if you could merge it !

### CODE REVIEW

**Comment by PawelAwmous** [comment]
I like your idea however I can't accept your pull request because it breaks class naming:

- right now to init the class you do `$pinterest = new \PinterestPinner\Pinner;`, if I'd merge your changes it would have to be `$pinterest = new PinterestPinner\Pinner_Guzzle;` which would end up with errors on all web services using my library, `Pinner` cannot be abstract,

- don't use `_` in a class name, there are namespaces.

The only way I could imagine this is to inject your new `Pinner_Guzzle` class as dependency, so for example by default it would be:
```php
public function __construct(\PinterestPinner\HttpClients\ClientInterface $client = null) {
    $this->httpClient = is_object($client) ? $client : new \PinterestPinner\HttpClients\Guzzle;
}
```
I added `ClientInterface` so we are sure the injected class contains all the required methods. Now you can insert your own client class:
```php
$pinterest = new \PinterestPinner\Pinner(new \PinterestPinner\HttpClients\Guzzle);
```
that way Guzzle is default but you can also use your own `$client`.

Please note the above code samples are just a rough example, not a final code.

**Comment by dzafel** [comment]
I like your idea however I can't accept your pull request because it breaks class naming:

- right now to init the class you do `$pinterest = new \PinterestPinner\Pinner;`, if I'd merge your changes it would have to be `$pinterest = new PinterestPinner\Pinner_Guzzle;` which would end up with errors on all web services using my library, `Pinner` cannot be abstract,

- don't use `_` in a class name, there are namespaces.

The only way I could imagine this is to inject your new `Pinner_Guzzle` class as dependency, so for example by default it would be:
```php
public function __construct(\PinterestPinner\HttpClients\ClientInterface $client = null) {
    $this->httpClient = is_object($client) ? $client : new \PinterestPinner\HttpClients\Guzzle;
}
```
I added `ClientInterface` so we are sure the injected class contains all the required methods. Now you can insert your own client class:
```php
$pinterest = new \PinterestPinner\Pinner(new \PinterestPinner\HttpClients\Guzzle);
```
that way Guzzle is default but you can also use your own `$client`.

Please note the above code samples are just a rough example, not a final code.

**Comment by gordielachance** [comment]
Hey ! Thanks for your reply.  I wonder if this is not making things over-complicated, but anyway, I've done it. ... What do u think about it ?

I personally prefer the first approach, it seems more clean to me, but it's up to you...

**Comment by dzafel** [comment]
Thanks. I don't have much time now to check it but I will do it later. For now I can see you didn't follow [PSRs](http://www.php-fig.org/psr/), for example:
- `Pinner-Client.php` and `Pinner-Client-Guzzle.php` are incorrect file names, they do not match namespaces and autoloader will simply have problems finding them,
- public methods and properties shouldn't be prepended with `_`
- also coding style issues - PSR-2

**Comment by gordielachance** [comment]
Hi, I did try to do what I could but you have to know that I'm quite an amateur so I don't have your programming skills ... :) I even didn't knew about namespaces.
Well, here's some more improvement.
Can't do much more with my skills !

**Comment by dzafel** [comment]
Thanks! Merged. I’ll fix the code soon, still a lot of issues.

**Comment by dzafel** [comment]
After some time spending on your code I had to revert last commit with your changes. I'm sorry, I appreciate your help, but it does not work as it should and the code is just very, very messy. Anyway thanks for the idea, maybe I will work on this within the next couple weeks, it needs few hours of work and testing. For now Guzzle is still required.

**Comment by gordielachance** [comment]
:/
ok, thanks for your feedback.
what's messy ?

2017-02-28 20:07 GMT+01:00 dzafel <notifications@github.com>:

**Pull request merged**
